package main

import (
	"os"
	"strings"
	"testing"
)

// TestLiveXuguSchedulerJobs exercises the database-scoped job path end to
// end. It intentionally creates a disabled no-op job so the test does not
// schedule application work. CI has no Xugu service, so this runs only with
// XUGU_LIVE_TEST=1 and the standard XUGU_LIVE_* variables.
func TestLiveXuguSchedulerJobs(t *testing.T) {
	if os.Getenv("XUGU_LIVE_TEST") != "1" {
		t.Skip("set XUGU_LIVE_TEST=1 with XUGU_LIVE_* connection settings to run the XuguDB integration test")
	}
	params := connectParams{
		Host:     os.Getenv("XUGU_LIVE_HOST"),
		Port:     parsePort(os.Getenv("XUGU_LIVE_PORT")),
		Database: os.Getenv("XUGU_LIVE_DATABASE"),
		Username: os.Getenv("XUGU_LIVE_USERNAME"),
		Password: os.Getenv("XUGU_LIVE_PASSWORD"),
	}
	if params.Host == "" || params.Database == "" || params.Username == "" || params.Password == "" {
		t.Fatal("XUGU_LIVE_HOST, XUGU_LIVE_DATABASE, XUGU_LIVE_USERNAME, and XUGU_LIVE_PASSWORD are required")
	}

	s := newServer()
	db, err := openDB(params)
	if err != nil {
		t.Fatal(err)
	}
	s.db = db
	s.params = params
	s.currentDatabase = params.Database
	defer s.disconnect()

	const jobName = "DBX_SCHEDULER_LIVE_TEST_JOB"
	cleanup := "EXEC DBMS_SCHEDULER.DROP_JOB('" + jobName + "', FALSE);"
	_ = s.execWithReconnect(cleanup)
	defer func() { _ = s.execWithReconnect(cleanup) }()

	// Use a real start timestamp and repeat expression, not only NULL defaults.
	// The subsequent drop/replay assertion verifies that the catalog values
	// generated by the server are valid CREATE_JOB inputs.
	create := "EXEC DBMS_SCHEDULER.CREATE_JOB('" + jobName + "', 'plsql_block', 'BEGIN NULL; END;', 0, SYSTIMESTAMP, 'FREQ=DAILY;BYHOUR=2;BYMINUTE=0', NULL, 'default_class', FALSE, FALSE, 'DBX scheduler integration test');"
	if err := s.execWithReconnect(create); err != nil {
		t.Fatalf("create scheduler job failed: %v", err)
	}

	schemas, err := s.listSchemas()
	if err != nil {
		t.Fatal(err)
	}
	if !containsXuguName(schemas, xuguSchedulerJobScope) {
		t.Fatalf("scheduler scope missing after job creation: %v", schemas)
	}

	jobs, err := s.listObjects(xuguSchedulerJobScope, metadataListConstraints{ObjectTypes: []string{"JOB"}})
	if err != nil {
		t.Fatal(err)
	}
	if !containsXuguObject(jobs, jobName) {
		t.Fatalf("scheduler job was not listed: %#v", jobs)
	}

	source, err := s.getObjectSource(xuguSchedulerJobScope, jobName, "JOB")
	if err != nil {
		t.Fatal(err)
	}
	ddl, _ := source["source"].(string)
	for _, want := range []string{"EXEC DBMS_SCHEDULER.CREATE_JOB", jobName, "'plsql_block'", "'BEGIN NULL; END;'", "FREQ=DAILY", "FALSE"} {
		if !strings.Contains(ddl, want) {
			t.Fatalf("reconstructed job DDL is missing %q: %s", want, ddl)
		}
	}
	if strings.Contains(ddl, "1816-03-30") {
		t.Fatalf("NULL END_T must not be reconstructed as the Xugu DATETIME sentinel: %s", ddl)
	}
	if !strings.Contains(ddl, "\n  NULL,\n  'default_class'") {
		t.Fatalf("NULL END_T must remain a SQL NULL argument in reconstructed DDL: %s", ddl)
	}
	if err := s.execWithReconnect(cleanup); err != nil {
		t.Fatalf("drop scheduler job before replay failed: %v", err)
	}
	if err := s.execWithReconnect(ddl); err != nil {
		t.Fatalf("replay reconstructed scheduler job DDL failed: %v\nDDL:\n%s", err, ddl)
	}
	replayed, err := s.listObjects(xuguSchedulerJobScope, metadataListConstraints{ObjectTypes: []string{"JOB"}})
	if err != nil {
		t.Fatal(err)
	}
	if !containsXuguObject(replayed, jobName) {
		t.Fatalf("scheduler job missing after DDL replay: %#v", replayed)
	}

	for _, statement := range []string{
		"EXEC DBMS_SCHEDULER.ENABLE('" + jobName + "');",
		"EXEC DBMS_SCHEDULER.RUN_JOB('" + jobName + "', TRUE);",
		"EXEC DBMS_SCHEDULER.DISABLE('" + jobName + "', FALSE);",
	} {
		if err := s.execWithReconnect(statement); err != nil {
			t.Fatalf("job lifecycle operation failed (%s): %v", statement, err)
		}
	}
}
