[package]
name = "dbx-plugin-cli"
version = "0.1.9"
edition = "2021"
license = "Apache-2.0"
description = "Scaffold and package DBX plugins"

[workspace]

[[bin]]
name = "dbx-plugin"
path = "src/main.rs"

[dependencies]
dbx-plugin-packager = { version = "0.1.0", path = "../packager" }
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"

[dev-dependencies]
tempfile = "3"
